# Step 1: PostgreSQL only with secrets
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  
  # Database configuration (matching keycloak2.conf)
  database:
    name: optimus
    port: 5432
  
  # Secrets configuration
  secrets:
    enabled: true
    postgresPassword: postgres
    username: optimus
    password: optimus
  
  primary:
    persistence:
      enabled: true
      storageClass: ""
      size: 8Gi
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    
    service:
      type: NodePort
      port: 5432 
