apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: supervisor-agent
spec:
  prompt: You are a supervisor agent. You have access to tools that are agents that can perform tasks. Present the complete output to the user. WHen a procurement order is requested, always present the full order table in the output.
  modelRef:
    name: default
  tools:
    - type: custom
      name: mlrun-agent-as-tool
    - type: custom
      name: maintenance-agent-as-tool
    - type: custom
      name: procurement-agent-as-tool

